#!/usr/bin/python3
"""Sanitize Aurvek's staging blocklist and safely reload nginx.

This file must be installed as a root-owned executable outside /opt/aurvek.
The web application is intentionally allowed to write only the staging file.
"""

from __future__ import annotations

import ipaddress
import os
import re
import stat
import subprocess
import tempfile
from pathlib import Path

try:
    import pwd
except ImportError:  # pragma: no cover - the helper only executes on Linux
    pwd = None


SOURCE = Path("/opt/aurvek-data/nginx_blocklist.conf")
TARGET = Path("/etc/nginx/aurvek/blocklist.map")
EXPECTED_SOURCE_USER = "aurvek"
MAX_SOURCE_BYTES = 1_048_576
MAX_ENTRIES = 10_000
ENTRY_RE = re.compile(r"([^\s;]+)\s+1;")
NGINX_TEST_COMMAND = ("/usr/sbin/nginx", "-t", "-q")
NGINX_RELOAD_COMMAND = ("/usr/bin/systemctl", "reload", "nginx.service")


class SyncError(RuntimeError):
    """A candidate could not be safely promoted."""


def _read_staging_file(path: Path = SOURCE) -> str:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags)
    except OSError as exc:
        raise SyncError(f"cannot open staging file: {exc}") from exc

    try:
        file_stat = os.fstat(fd)
        if not stat.S_ISREG(file_stat.st_mode):
            raise SyncError("staging path is not a regular file")
        if file_stat.st_size > MAX_SOURCE_BYTES:
            raise SyncError(f"staging file exceeds {MAX_SOURCE_BYTES} bytes")

        if pwd is None:
            raise SyncError("POSIX account lookup is unavailable")
        expected_uid = pwd.getpwnam(EXPECTED_SOURCE_USER).pw_uid
        if file_stat.st_uid != expected_uid:
            raise SyncError("staging file has an unexpected owner")
        if file_stat.st_mode & stat.S_IWOTH:
            raise SyncError("staging file must not be world-writable")

        with os.fdopen(fd, "rb", closefd=False) as handle:
            raw = handle.read(MAX_SOURCE_BYTES + 1)
        if len(raw) > MAX_SOURCE_BYTES:
            raise SyncError(f"staging file exceeds {MAX_SOURCE_BYTES} bytes")
        try:
            return raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise SyncError("staging file is not valid UTF-8") from exc
    finally:
        os.close(fd)


def _is_safe_address(address: ipaddress.IPv4Address | ipaddress.IPv6Address) -> bool:
    return address.is_global


def sanitize_candidate(content: str) -> tuple[str, int]:
    """Return canonical nginx map entries or reject the complete candidate."""
    addresses: set[ipaddress.IPv4Address | ipaddress.IPv6Address] = set()

    for line_number, raw_line in enumerate(content.splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        match = ENTRY_RE.fullmatch(line)
        if not match:
            raise SyncError(f"invalid syntax on line {line_number}")
        try:
            address = ipaddress.ip_address(match.group(1))
        except ValueError as exc:
            raise SyncError(f"invalid IP address on line {line_number}") from exc
        if getattr(address, "scope_id", None) is not None:
            raise SyncError(f"scoped IPv6 address on line {line_number}")
        if not _is_safe_address(address):
            raise SyncError(f"non-public IP address on line {line_number}")

        addresses.add(address)
        if len(addresses) > MAX_ENTRIES:
            raise SyncError(f"candidate exceeds {MAX_ENTRIES} entries")

    ordered = sorted(addresses, key=lambda address: (address.version, int(address)))
    lines = [
        "# Generated by aurvek-nginx-blocklist-sync",
        "# Root-owned sanitized copy; do not edit",
    ]
    lines.extend(f"{address.compressed} 1;" for address in ordered)
    return "\n".join(lines) + "\n", len(ordered)


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    temporary_path = ""
    try:
        fd, temporary_path = tempfile.mkstemp(prefix=".blocklist-", dir=path.parent)
        with os.fdopen(fd, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, 0o644)
        os.replace(temporary_path, path)
        temporary_path = ""

        directory_fd = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        if temporary_path:
            try:
                os.unlink(temporary_path)
            except FileNotFoundError:
                pass


def _run(command: tuple[str, ...], description: str) -> None:
    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    if result.returncode == 0:
        return
    detail = (result.stderr or result.stdout or "unknown error").strip()
    raise SyncError(f"{description} failed: {detail}")


def _restore_target(previous: bytes | None) -> None:
    if previous is None:
        try:
            TARGET.unlink()
        except FileNotFoundError:
            pass
    else:
        _atomic_write(TARGET, previous)


def sync() -> int:
    sanitized, entry_count = sanitize_candidate(_read_staging_file())
    candidate = sanitized.encode("ascii")
    previous = TARGET.read_bytes() if TARGET.exists() else None

    if previous == candidate:
        print(f"Aurvek nginx blocklist unchanged ({entry_count} entries)")
        return entry_count

    _atomic_write(TARGET, candidate)
    try:
        _run(NGINX_TEST_COMMAND, "nginx configuration test")
    except Exception:
        _restore_target(previous)
        raise

    try:
        _run(NGINX_RELOAD_COMMAND, "nginx reload")
    except Exception:
        _restore_target(previous)
        try:
            _run(NGINX_TEST_COMMAND, "restored nginx configuration test")
            _run(NGINX_RELOAD_COMMAND, "restored nginx reload")
        except Exception as rollback_exc:
            raise SyncError(f"nginx reload and rollback failed: {rollback_exc}") from rollback_exc
        raise

    print(f"Aurvek nginx blocklist applied ({entry_count} entries)")
    return entry_count


def main() -> int:
    try:
        sync()
    except (OSError, KeyError, subprocess.SubprocessError, SyncError) as exc:
        print(f"Aurvek nginx blocklist sync failed: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
